import Head from 'next/head';

import AppNavBar from '../componentes/AppNavBar';

import AppCardBullets from '../componentes/AppCardBullets';


export default function Home() {
  // jsx (codigo html com react)
  let title = 'Meu primeiro WebApp!';

  const bullets_today = [
    {type: 'event', title: 'Momento síncrono sobre componente react'},
    {type: 'task', title: 'Palavras chaves - Bullet jornal, github issues'}
  ];
  const bullets_tomorrow = [
    {type: 'task', title: 'Priorizar as palavras-chave'},
    {type: 'task', title: 'Pesquisar imagens das principais palavras-chave'},
    {type: 'task', title: 'Prototipar UI'}
  ];

  return (
    <div >
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AppNavBar title={title}></AppNavBar>
        <AppCardBullets date="15/09/2021" bullets={bullets_today}></AppCardBullets>
        <AppCardBullets date="19/09/2021" bullets={bullets_tomorrow}></AppCardBullets>
      </main>

      
    </div>
  )
}
