import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  // jsx (codigo html com react)
  let title = 'Meu primeiro WebApp!';
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {title}
        </h1>
        <h2 font-size='15px;'>Minhas tarefas diárias</h2>

      </main>

      <footer className={styles.footer}>
          Powered by{' '}
         Infoweb 2021
      </footer>
    </div>
  )
}
